# Generated by Django 6.0.5 on 2026-05-14 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_conversation_assignee'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên nhà cung cấp')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
                ('is_active', models.BooleanField(default=False, verbose_name='Kích hoạt')),
            ],
            options={
                'verbose_name': 'Nhà cung cấp AI',
                'verbose_name_plural': 'Các nhà cung cấp AI',
            },
        ),
        migrations.CreateModel(
            name='APIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Tên Model')),
                ('is_active', models.BooleanField(default=False, verbose_name='Kích hoạt')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_models', to='app.aiprovider', verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name': 'Model API',
                'verbose_name_plural': 'Các Model API',
                'unique_together': {('provider', 'model_name')},
            },
        ),
    ]
